#!/usr/bin/env node

const {db, User} = require('../models');
const {users} = require('../data');


(async () => {
  await User.bulkCreate(users.map(([username, name, password, email]) => ({username, name, password, email})));
  db.close();
})();
